### ISSUE TITLE
[Feature request] Support Visual Studio Code

### ISSUE THREAD

**Issue by ndh103** [pautx24/VsNamespaceFixer#40]
This is really helpful and I think it would be really great if you can make this available for VS Code

**Comment by pauer24** [comment]
Wooow! thanks a ton for the insight!

Though I made this tool (and recently upgraded to vs 2022) for my own purposes. Since I do not code C# in VS Code I'm afraid I won't do it on my own...

But feel free to do it yourself, and do not hesitate to ask for support. I'll be thrilled to give you a hand anytime :)

Cheers!

P.
